/// Dog breeds list
class DogBreeds {
  DogBreeds._();
  
  static const List<String> all = [
    'Mixed Breed',
    'Labrador Retriever',
    'German Shepherd',
    'Golden Retriever',
    'French Bulldog',
    'Bulldog',
    'Poodle',
    'Beagle',
    'Rottweiler',
    'German Shorthaired Pointer',
    'Dachshund',
    'Pembroke Welsh Corgi',
    'Australian Shepherd',
    'Yorkshire Terrier',
    'Boxer',
    'Cavalier King Charles Spaniel',
    'Doberman Pinscher',
    'Great Dane',
    'Miniature Schnauzer',
    'Siberian Husky',
    'Shih Tzu',
    'Boston Terrier',
    'Bernese Mountain Dog',
    'Pomeranian',
    'Havanese',
    'Shetland Sheepdog',
    'Border Collie',
    'Brittany',
    'English Springer Spaniel',
    'Cocker Spaniel',
    'Maltese',
    'Chihuahua',
    'Pit Bull Terrier',
    'Staffordshire Bull Terrier',
    'Jack Russell Terrier',
    'Australian Cattle Dog',
    'Bichon Frise',
    'Akita',
    'West Highland White Terrier',
    'Bloodhound',
    'Newfoundland',
    'Saint Bernard',
    'Weimaraner',
    'Bull Terrier',
    'Greyhound',
    'Whippet',
    'Irish Setter',
    'Scottish Terrier',
    'Alaskan Malamute',
    'Basset Hound',
    'Other',
  ];
}

/// Cat breeds list
class CatBreeds {
  CatBreeds._();
  
  static const List<String> all = [
    'Domestic Shorthair',
    'Domestic Longhair',
    'Domestic Medium Hair',
    'Persian',
    'Maine Coon',
    'Ragdoll',
    'British Shorthair',
    'Abyssinian',
    'Siamese',
    'Scottish Fold',
    'Sphynx',
    'Bengal',
    'Russian Blue',
    'Norwegian Forest Cat',
    'Birman',
    'Oriental Shorthair',
    'Devon Rex',
    'Exotic Shorthair',
    'Burmese',
    'American Shorthair',
    'Savannah',
    'Himalayan',
    'Tonkinese',
    'Ragamuffin',
    'Turkish Angora',
    'Manx',
    'Japanese Bobtail',
    'Cornish Rex',
    'Chartreux',
    'Bombay',
    'Balinese',
    'Egyptian Mau',
    'Siberian',
    'Somali',
    'Turkish Van',
    'Other',
  ];
}
